"""Random seeds, centralized — one named constant per notebook (and per
role within a notebook: _BL, _FINAL, _DEFAULT).

Values are EXACTLY the ones used to produce the thesis results; do not
change them. They differ across notebooks on purpose. Constant names encode
the notebook that uses them (stage/folder/notebook); the full literal ->
constant mapping from the refactor is preserved locally in
local_archive/seed_mapping_report.md.

Used via `from src.seeds import SEED_...`.
"""

SEED_DATA_NEWS_COLLECTION = 42
SEED_PORTFOLIO_BENCHMARKS_MVO_CAPM_V3_2_0 = 420
SEED_PORTFOLIO_DRL_PPO_V9_1_3 = 42
SEED_PORTFOLIO_DRL_PPO_V9_1_X_NEWS = 347892
SEED_PORTFOLIO_DRL_PPO_V9_1_X_NEWS_DEFAULT = 42
SEED_PORTFOLIO_DRL_PPO_V9_1_X_REDDIT = 21082003
SEED_PORTFOLIO_DRL_PPO_V9_1_X_REDDIT_DEFAULT = 42
SEED_PORTFOLIO_DRL_PPO_V9_1_X_REDDIT_NEWS = 69
SEED_PORTFOLIO_DRL_PPO_V9_1_X_REDDIT_NEWS_DEFAULT = 42
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_2 = 123
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_2_BL = 123123
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_X_NEWS = 123123
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_X_NEWS_BL = 21082001
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_X_REDDIT = 123123
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_X_REDDIT_BL = 123
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_X_REDDIT_NEWS = 123123
SEED_PORTFOLIO_LSTM_RETURNS_V5_2_X_REDDIT_NEWS_BL = 69
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_2 = 123
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_2_FINAL = 21082003
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_X_NEWS = 123124
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_X_NEWS_FINAL = 123123123
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_X_REDDIT = 123124
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_X_REDDIT_FINAL = 123123
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_X_REDDIT_NEWS = 123124
SEED_PORTFOLIO_LSTM_SHARPE_V3_2_X_REDDIT_NEWS_FINAL = 123123
SEED_SENTIMENT_NEWS_V1_BERT_EMBEDDINGS = 42
SEED_SENTIMENT_NEWS_V1_SECTOR_EMBEDDINGS = 42
SEED_SENTIMENT_NEWS_V1_TFIDF_EMBEDDINGS = 42
SEED_SENTIMENT_NEWS_V2_BERT_EMBEDDINGS = 42
SEED_SENTIMENT_NEWS_V2_SECTOR_EMBEDDINGS = 42
SEED_SENTIMENT_NEWS_V2_TFIDF_EMBEDDINGS = 42
SEED_SENTIMENT_NEWS_VF2_SECTOR_EMBEDDINGS = 42
SEED_SENTIMENT_NEWS_VF2_TFIDF_EMBEDDINGS = 42
SEED_SENTIMENT_REDDIT_V1_MODEL = 42
SEED_SENTIMENT_REDDIT_V2_MODEL = 42
SEED_SENTIMENT_REDDIT_V4_MODEL = 42
